from enum import Enum

class ProcessStatuses(Enum):
    LETTER_LOADED = 0
    LETTER_PARSING_FOR_SCENES = 1
    LETTER_READY_FOR_IMAGE_GENERATING = 2
    LETTER_IN_IMAGE_GENERATION_PROCESS = 3
    LETTER_READY_FOR_VIDEO_GENERATION = 4
    LETTER_IN_VIDEO_GENERATION_PROCESS = 4